name: Starting bot ...

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: echo it
        run: |
          echo "ok lets start to test workflows"
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: get ready ubuntu for run
        run: |
          echo "lets start"
          sudo apt update -y
          sudo apt upgrade -y
          echo "Ubuntu ready"
          node -v
      - name: run bot
        run: |
          sudo apt install -y make python build-essential
          curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
          sudo apt-get install -y nodejs
          echo "all ready to run"
          node -v
          npm install
          node server

      - run: echo "everything done!"
